[package]
name = "super-copier"
version = "0.1.0"
edition = "2021"
default-run = "super-copier"

[[bin]]
name = "super-copier"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
crossbeam-channel = "0.5.17"
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "links", "wgpu", "x11", "wayland"] }
egui = "0.36.2"
engine = { version = "0.1.0", path = "../engine" }
notify-rust = "4.18.0"
rfd = "0.17.2"
